/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_DevDayCP_JNI_ProdutoViewModel */

#ifndef _Included_com_DevDayCP_JNI_ProdutoViewModel
#define _Included_com_DevDayCP_JNI_ProdutoViewModel
#ifdef __cplusplus
extern "C" {
#endif

//int JNI_OnLoad(JavaVM* vm, void* reserved);
/*
 * Class:     com_DevDayCP_JNI_ProdutoViewModel
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_DevDayCP_JNI_ProdutoViewModel_initialize(JNIEnv *env, jobject obj);

/*
 * Class:     com_DevDayCP_JNI_ProdutoViewModel
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_DevDayCP_JNI_ProdutoViewModel_toString(JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
